postsubmits:
  rocky-linux/peridot:
    - name: post-peridot-unit-test
      always_run: true
      decorate: true
      branches:
        - main
      spec:
        tolerations:
          - key: peridot.rockylinux.org/workflow-tolerates-arch
            operator: Equal
            value: amd64
            effect: NoSchedule
        nodeSelector:
          peridot.rockylinux.org/workflow-tolerates-arch: amd64
        containers:
          - image: quay.io/peridot/ci:v0.3.19
            command:
              - hack/unit_tests.sh

    - name: post-peridot-build-all-frontends
      always_run: true
      decorate: true
      branches:
        - main
      spec:
        tolerations:
          - key: peridot.rockylinux.org/workflow-tolerates-arch
            operator: Equal
            value: amd64
            effect: NoSchedule
        nodeSelector:
          peridot.rockylinux.org/workflow-tolerates-arch: amd64
        containers:
          - image: quay.io/peridot/ci:v0.3.19
            command:
              - hack/build_all_frontends.sh

    - name: post-peridot-deploy-impacted
      always_run: true
      decorate: true
      branches:
        - main
      spec:
        serviceAccountName: peridot-deploy
        tolerations:
          - key: peridot.rockylinux.org/workflow-tolerates-arch
            operator: Equal
            value: amd64
            effect: NoSchedule
        nodeSelector:
          peridot.rockylinux.org/workflow-tolerates-arch: amd64
        containers:
          - image: quay.io/peridot/ci:v0.3.19
            command:
              - hack/deploy_impacted.sh
